kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: qsE7/CJY/J8txo8V5z/ktIvcANHhV6/DLwIfkpNUl9Y=
      - identity: {}
